### ISSUE TITLE
Add mute action please

### ISSUE THREAD

**Issue by okmoon** [adriancampos/Swipeup-Utility#13]

**Comment by adriancampos** [comment]
I've been working on screen capture, that should be here soon.
Are you referring to Android's Do Not Disturb? I'll see if I can interface with that

**Comment by adriancampos** [comment]
Do Not Disturb toggles are now included in Swipeup Utility Pro (Donate) V1.6, which is currently in beta :) 
https://play.google.com/apps/testing/com.AdrianCampos.gnsddonate

Send me an email if you haven't purchased the paid version.
