### ISSUE TITLE
Is there a way to Launch as a swipe up gesture through shortcut

### ISSUE THREAD

**Issue by dredd9877** [adriancampos/Swipeup-Utility#18]
Instead of having to swipe up I want to make a shortcut that when I click it it'll act as if I performed the gesture swipe up

**Comment by dredd9877** [comment]
If it applies I do have all the Tasker apps including autoinput I just don't know how to configure it that way

**Comment by adriancampos** [comment]
A shortcut on the home screen? That shouldn't be too difficult to implement..

**Comment by dredd9877** [comment]
![screenshot_2016-08-15-23-57-37](https://cloud.githubusercontent.com/assets/20268031/17688360/3987baa4-6344-11e6-86d0-3b71bdd31c28.png)

I know

**Comment by adriancampos** [comment]
Whoops, I meant that it shouldn't be too hard for me to implement in a future version. Be on the lookout for an update soon ;)

**Comment by adriancampos** [comment]
I've added support in version 2.0.7, which is currently in beta. Let me know what you think :) 
https://play.google.com/apps/testing/com.AdrianCampos.swipeuputility


![Shortcut Launchapp animation](https://cloud.githubusercontent.com/assets/6026391/17791147/94cd3234-654e-11e6-9209-6e353d2ffe69.gif)
