### ISSUE TITLE
Ability to reorder items in popup menu

### ISSUE THREAD

**Issue by Gitoffthelawn** [adriancampos/Swipeup-Utility#5]
Can you add the ability to reorder items in the popup menu?

**Comment by adriancampos** [comment]
I've reworked the popup, implemented reordering, and am almost ready to release an update. Keep your eyes peeled! ( https://goo.gl/photos/J1JtyuDpXcXAgQLZ7 )
Thanks for your support!

**Comment by Gitoffthelawn** [comment]
Thanks!

**Comment by adriancampos** [comment]
Swipeup Utility 2.0's in beta and fixes this.
https://play.google.com/apps/testing/com.AdrianCampos.swipeuputility

**Comment by Gitoffthelawn** [comment]
Thanks... I'll have to take a look at it again!
