### ISSUE TITLE
Switching from multiple items to just one item still results in popup

### ISSUE THREAD

**Issue by Gitoffthelawn** [adriancampos/Swipeup-Utility#6]
Switching from multiple items to just one item still results in a popup. Instead, it should just load the app (which is what it does if the user doesn't start with multiple items selected).

Workaround: Clear cache and data for the Swipeup-Utility.

**Comment by adriancampos** [comment]
Thanks for pointing that out!

Another workaround would be to press the back button and leave multi-select mode, and tap on the single item, but I agree that the popup should not show when only one item is selected.

Thanks again, look for that in the next release as well!

**Comment by Gitoffthelawn** [comment]
You're welcome!  Thanks for making Swipe-up!

I had some issues with pressing the back button to leave multi-select mode; I tried over and over to get it out of multi-select mode, but everything I tried didn't work... so I just cleared the cache and data, and all was good!

**Comment by adriancampos** [comment]
Swipeup Utility 2.0's in beta and fixes this.
https://play.google.com/apps/testing/com.AdrianCampos.swipeuputility

**Comment by Gitoffthelawn** [comment]
Thanks!
