### ISSUE TITLE
request: Marshmallow support

### ISSUE THREAD

**Issue by patrickdo** [adriancampos/Swipeup-Utility#7]

**Comment by adriancampos** [comment]
Google changed things in the way that swipeup is handled, so I'm no longer able to tell when the home button is swiped/held. :/
For now, it looks like a workaround is to disable the Now on Tap feature, which will revert the system to the old way of doing things. I'm working on an update to properly fix this, though, so look for that in the near future.
Thanks for letting me know, and sorry about the inconvenience.

**Comment by patrickdo** [comment]
Thanks for the quick reply. any idea how to have that long press of home
button open up voice search?

**Comment by adriancampos** [comment]
If you get Swipeup Utility to work, you'll select 'Voice Search' in Swipeup Utility's Choose Action screen. I don't have a Marshmallow device at the moment, but when I get my hands on one I'll let you know.

**Comment by stevenqzhang** [comment]
@adriancampos - I tried the workaround of disabling now on tap, but long-pressing still goes to the google search screen. Swipe up isn't detected

**Comment by adriancampos** [comment]
Thanks, @stevenqzhang! Default apps - Assist & Voice Input - Assist App seems to be the best workaround. I'm working on an update that'll nicely guide the user through that, but it looks like we'll be stuck with that in 6.0+

**Comment by Oldpedro** [comment]
Setting swipeup as the assist app as you suggest does work perfectly. I'd really miss having my calculator to hand at all times!

**Comment by adriancampos** [comment]
Okay, version 1.9.4 with Marshmallow support is finally out! You can opt into the beta here: https://play.google.com/apps/testing/com.AdrianCampos.swipeuputility
Thank you for your patience, and let me know how it works out.
